[http.middlewares]
  [http.middlewares.middlewares-basic-auth]
    [http.middlewares.middlewares-basic-auth.basicAuth]
      realm = "Traefik2 Basic Auth"
      users = ["fileserver:$1$amKLMVom$hMiWve.ERT.IE1saXUcze/"]

[http.middlewares.middlewares-oauth]
  [http.middlewares.middlewares-oauth.forwardAuth]
    address = "http://oauth:4181" # Make sure you have the OAuth service in docker-compose.yml
    trustForwardHeader = true
    authResponseHeaders = ["X-Forwarded-User"]

[http.middlewares.middlewares-rate-limit]
  [http.middlewares.middlewares-rate-limit.rateLimit]
    average = 100
    burst = 50

[http.middlewares.middlewares-secure-headers]
  [http.middlewares.middlewares-secure-headers.headers]
    accessControlAllowMethods= ["GET", "OPTIONS", "PUT"]
    accessControlMaxAge = 100
    hostsProxyHeaders = ["X-Forwarded-Host"]
    sslRedirect = true
    stsSeconds = 63072000
    stsIncludeSubdomains = true
    stsPreload = true
    frameDeny = true
    forceSTSHeader = true 
    contentTypeNosniff = true 
    browserXssFilter = true 
    referrerPolicy = "same-origin"
    featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';" 

  [http.middlewares.middlewares-secure-headers.headers.customResponseHeaders]
    X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex,"
    server = ""


