# HTTP middlewares - enables basic auth & oauth -> can be used as labels or inside traefik.toml file

[http.middlewares]
  [http.middlewares.chain-no-auth]
    [http.middlewares.chain-no-auth.chain]
      middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers"]

  [http.middlewares.chain-basic-auth]
    [http.middlewares.chain-basic-auth.chain]
      middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers", "middlewares-basic-auth"]

  [http.middlewares.chain-oauth]
    [http.middlewares.chain-oauth.chain]
      middlewares = [ "middlewares-rate-limit", "middlewares-secure-headers", "middlewares-oauth"]
      
  [http.middlewares.middlewares-basic-auth]
    [http.middlewares.middlewares-basic-auth.basicAuth]
      users = [
        "fileserver:$apr1$2bw5v07s$iHVesZVIYS1wJTXyq3nwK0",
      ]
      realm = "Traefik2 Basic Auth"

  [http.middlewares.middlewares-rate-limit]
    [http.middlewares.middlewares-rate-limit.rateLimit]
      average = 100
      burst = 50

  [http.middlewares.middlewares-secure-headers]
    [http.middlewares.middlewares-secure-headers.headers]
      accessControlAllowMethods= ["GET", "OPTIONS", "PUT"]
      accessControlMaxAge = 100
      hostsProxyHeaders = ["X-Forwarded-Host"]
      sslRedirect = true
      stsSeconds = 63072000
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true 
      contentTypeNosniff = true 
      browserXssFilter = true 
      referrerPolicy = "same-origin" 
      featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';" 
      [http.middlewares.middlewares-secure-headers.headers.customResponseHeaders]
        X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex,"
        server = ""

  [http.middlewares.middlewares-oauth]
    [http.middlewares.middlewares-oauth.forwardAuth]
      address = "http://oauth:4181" # Make sure you have the OAuth service in docker-compose.yml
      trustForwardHeader = true
      authResponseHeaders = ["X-Forwarded-User"]

# Traefik dashboard router
[http.routers.traefikapi]
  rule = "Host(`traefik.timo.be`)"
  service = "api@internal"
  entryPoints = ["https"]
  middlewares = ["chain-oauth"]

  [http.routers.traefikapi.tls]
    certResolver = "leresolver"

# Unraid dashboard - unraid ui is configured to run on port 81
[http.services]
  [http.services.unraid-svc.loadBalancer]
    [[http.services.unraid-svc.loadBalancer.servers]]
      url = "http://192.168.0.3:81/"
    
[http.routers.unraid-rtr]
  rule = "Host(`unraid.timo.be`)"
  service = "unraid-svc"
  entryPoints = ["https"]
  middlewares = ["chain-no-auth"]

  [http.routers.unraid-rtr.tls]
    certResolver = "leresolver"